project_name: hperf

release:
   name_template: "Release version {{.Version}}"

   github:
    owner: minio
    name: hperf

before:
  hooks:
    - go mod tidy

builds:
  -
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
      - ppc64le
      - s390x
    ignore:
      - goos: windows
        goarch: arm64
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
      - --tags=kqueue
    ldflags:
      - "-s -w -X main.version={{.Version}}"
    dir: .
    main: ./cmd/cli

archives:
  -
    name_template: "{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}"
    format: binary

nfpms:
  -
    vendor: MinIO, Inc.
    homepage: https://github.com/minio/hperf
    maintainer: MinIO Development <dev@min.io>
    description: Nperf tool performs N peers to N peers cross network benchmark measuring RX/TX bandwidth for each peers
    license: GNU Affero General Public License v3.0
    formats:
      - deb
      - rpm

signs:
  -
    signature: "${artifact}.minisig"
    cmd: "sh"
    args:
      - '-c'
      - 'minisign -s /media/${USER}/minio/minisign.key -Sm ${artifact} < /media/${USER}/minio/minisign-passphrase'
    artifacts: all

snapshot:
  name_template: v0.0.0@{{.ShortCommit}}

changelog:
  sort: asc

dockers:
- image_templates:
  - "quay.io/minio/hperf:{{ .Tag }}-amd64"
  use: buildx
  dockerfile: Dockerfile
  extra_files:
    - LICENSE
    - CREDITS
  build_flag_templates:
  - "--platform=linux/amd64"
- image_templates:
  - "quay.io/minio/hperf:{{ .Tag }}-ppc64le"
  use: buildx
  dockerfile: Dockerfile
  extra_files:
    - LICENSE
    - CREDITS
  build_flag_templates:
  - "--platform=linux/ppc64le"
- image_templates:
  - "quay.io/minio/hperf:{{ .Tag }}-s390x"
  use: buildx
  dockerfile: Dockerfile
  extra_files:
    - LICENSE
    - CREDITS
  build_flag_templates:
  - "--platform=linux/s390x"
- image_templates:
  - "quay.io/minio/hperf:{{ .Tag }}-arm64"
  use: buildx
  goarch: arm64
  dockerfile: Dockerfile
  extra_files:
    - LICENSE
    - CREDITS
  build_flag_templates:
  - "--platform=linux/arm64"
docker_manifests:
- name_template: quay.io/minio/hperf:{{ .Tag }}
  image_templates:
  - quay.io/minio/hperf:{{ .Tag }}-amd64
  - quay.io/minio/hperf:{{ .Tag }}-arm64
  - quay.io/minio/hperf:{{ .Tag }}-ppc64le
  - quay.io/minio/hperf:{{ .Tag }}-s390x
- name_template: quay.io/minio/hperf:latest
  image_templates:
  - quay.io/minio/hperf:{{ .Tag }}-amd64
  - quay.io/minio/hperf:{{ .Tag }}-arm64
  - quay.io/minio/hperf:{{ .Tag }}-ppc64le
  - quay.io/minio/hperf:{{ .Tag }}-s390x
