---
apiVersion: v1
kind: Service
metadata:
  name: hperf
  labels:
    app: hperf
spec:
  publishNotReadyAddresses: true
  clusterIP: None
  ports:
    - port: 9999
      name: http1
  selector:
    app: hperf
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: hperf
  labels:
    app: hperf
spec:
  serviceName: hperf
  podManagementPolicy: Parallel
  replicas: 6
  selector:
    matchLabels:
      app: hperf
  template:
    metadata:
      name: hperf
      labels:
        app: hperf
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - hperf
              topologyKey: "kubernetes.io/hostname"
      containers:
        - name: hperf
          image: "quay.io/minio/hperf"
          imagePullPolicy: Always
          args:
            - hperf-0.hperf.${NAMESPACE}.svc.cluster.local
            - hperf-1.hperf.${NAMESPACE}.svc.cluster.local
            - hperf-2.hperf.${NAMESPACE}.svc.cluster.local
            - hperf-3.hperf.${NAMESPACE}.svc.cluster.local
            - hperf-4.hperf.${NAMESPACE}.svc.cluster.local
            - hperf-5.hperf.${NAMESPACE}.svc.cluster.local
          ports:
            - name: http1
              containerPort: 9999
