apiVersion: v1
kind: Service
metadata:
  name: {{ template "hperf.fullname" . }}
  labels:
    app: hperf
spec:
  publishNotReadyAddresses: true
  clusterIP: None  
  ports:
    - port: {{ .Values.hperf.port }}
      name: http1
  selector:
    app: hperf
